### ISSUE TITLE
验证集精度一直在0.5几附近徘徊

### ISSUE THREAD

**Issue by alongwilliam** [pengming617/text_matching#1]
楼主，我跑你的ESIM模型，还有你的数据，训练集就0.9几，可是验证集从一开始就0.5几，这是什么情况呢？

**Comment by stormbirds** [comment]
> 楼主，我跑你的ESIM模型，还有你的数据，训练集就0.9几，可是验证集从一开始就0.5几，这是什么情况呢？

我同样用作者的数据跑ESIM模型，训练集和验证集都是0.5几，而且不管迭代多少次都一样，应该是参数有问题，或者模型不合理，初学暂时看不出那的问题。

**Comment by pengming617** [comment]
谢谢你的问题，我最近关注下这个问题，修改后会告诉您

**Comment by Jiapeilei** [comment]
你好，请问这个问题解决了吗？这个问题对这个模型很重要。

**Comment by zsweet** [comment]
帮回复下，问题出在了data_prepare的read_file，如下修改```return texta_new,textb_new,tags_vec# texta_new[:5000], textb_new[:5000], tags_vec[:5000]```

**Comment by pengming617** [comment]
今晚修改后上传


 
---原始邮件---
发件人: "Jiapeilei"<notifications@github.com>
发送时间: 2019年5月16日(星期四) 下午2:21
收件人: "pengming617/text_matching"<text_matching@noreply.github.com>;
抄送: "pengming617"<549639484@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [pengming617/text_matching] 验证集精度一直在0.5几附近徘徊 (#1)



你好，请问这个问题解决了吗？这个问题对这个模型很重要。

**Comment by pengming617** [comment]
多谢提醒，最近一直在忙，没有时间处理这些，晚点回去修改


 
---原始邮件---
发件人: "Zhang shiwei"<notifications@github.com>
发送时间: 2019年5月17日(星期五) 下午4:33
收件人: "pengming617/text_matching"<text_matching@noreply.github.com>;
抄送: "pengming617"<549639484@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [pengming617/text_matching] 验证集精度一直在0.5几附近徘徊 (#1)



帮回复下，问题出在了data_prepare的read_file，如下修改return texta_new,textb_new,tags_vec# texta_new[:5000], textb_new[:5000], tags_vec[:5000]

**Comment by pengming617** [comment]
已修改，多谢各位

**Comment by bzqweiyi** [comment]
1、现在模型的验证精度还是不高，请问问题出在哪里了？ 我自己尝试改变一些参数，但结果还是不理想。
2、输出的s有两个分数，eg:tf.argmax([0.82, 0.18] )得到结果，y=0。这里是否表示两句话模型预测的结果为不相似？

**Comment by pengming617** [comment]
请问下您模型的精度大概多少呢  这个数据集上目前最好的F1在0.86左右吧  我的github里面有一个项目就是利用bert中文预训练模型fine-tuning后的结果  eval_accuracy = 0.88093615 test_accuracy = 0.86256  可以尝试下不分词,或者利用预训练好的词向量 字向量来试一下  可能效果会好点

输出的s是分数,第一个为0的分数即不匹配,第二个为1的分数即匹配 一般情况下0.5是阈值  可以尝试下别的阈值  比如设置当1的分数大于0.6时才认为两句话相似等




------------------ 原始邮件 ------------------
发件人: "james"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 中午1:51
收件人: "pengming617/text_matching"<text_matching@noreply.github.com>; 
抄送: "彭明"<549639484@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [pengming617/text_matching] 验证集精度一直在0.5几附近徘徊 (#1)




1、现在模型的验证精度还是不高，请问问题出在哪里了？ 我自己尝试改变一些参数，但结果还是不理想。
 2、输出的s有两个分数，eg:tf.argmax([0.82, 0.18] )得到结果，y=0。这里是否表示两句话模型预测的结果为不相似？

**Comment by pengming617** [comment]
对了  之前的代码有一些问题  后来我又更新过一次  不知道您下载的那份代码是不是最新的




------------------ 原始邮件 ------------------
发件人: "james"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 中午1:51
收件人: "pengming617/text_matching"<text_matching@noreply.github.com>; 
抄送: "彭明"<549639484@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [pengming617/text_matching] 验证集精度一直在0.5几附近徘徊 (#1)




1、现在模型的验证精度还是不高，请问问题出在哪里了？ 我自己尝试改变一些参数，但结果还是不理想。
 2、输出的s有两个分数，eg:tf.argmax([0.82, 0.18] )得到结果，y=0。这里是否表示两句话模型预测的结果为不相似？

**Comment by bzqweiyi** [comment]
博主您好！
	代码直接从git上拉取的，应该是最新的，稍微修改下就可以进行训练了。 
	默认config里的参数效果没有好太多，于是我修改了一些参数，目前词向量的维度改到100维，隐藏层改为200，lr=0.002.迭代20次后，F1 0.584642 acc 0.603 左右，这个模型与您说的F1=0.86 还是有点距离的。不确定有哪些参数没设置合理。
	代码中先进行了分词，然后又进行分字符串拼接，相当于没有用分词进行训练的。 
	另外预训练的词向量，我们自己项目中有部分维基百科语料训练出的，不知道这个vec是否可以移植到我们ESIM的模型中直接进行使用。
	所以，想请教下博主，有什么好的指导建议。

**Comment by pengming617** [comment]
我说的0.86是指目前所有模型在这个数据集上最好的效果，不是esim这个，我晚点跑一下模型看看效果吧，之后在回复您




---原始邮件---
发件人: "james"<notifications@github.com>
发送时间: 2019年8月9日(星期五) 晚上6:10
收件人: "pengming617/text_matching"<text_matching@noreply.github.com>;
抄送: "State change"<state_change@noreply.github.com>;"pengming617"<549639484@qq.com>;
主题: Re: [pengming617/text_matching] 验证集精度一直在0.5几附近徘徊 (#1)


博主您好！ 
 代码直接从git上拉取的，应该是最新的，稍微修改下就可以进行训练了。  
 默认config里的参数效果没有好太多，于是我修改了一些参数，目前词向量的维度改到100维，隐藏层改为200，lr=0.002.迭代20次后，F1 0.584642 acc 0.603 左右，这个模型与您说的F1=0.86 还是有点距离的。不确定有哪些参数没设置合理。 
 代码中先进行了分词，然后又进行分字符串拼接，相当于没有用分词进行训练的。  
 另外预训练的词向量，我们自己项目中有部分维基百科语料训练出的，不知道这个vec是否可以移植到我们ESIM的模型中直接进行使用。 
 所以，想请教下博主，有什么好的指导建议。

**Comment by bzqweiyi** [comment]
好的，谢谢您！期待您的结果。
不过论文中该模型的效果可以达到0.88，而且据说很多公司都在用esim这个模型，效果还不错。

**Comment by pengming617** [comment]
你试着把config里的l2_lamda修改为0.0试试  我在调其他模型的时候修改过这个参数  可能是l_2损失太大了 即使loss在下降模型也没拟合  
修改为0后 我这边跑了两轮结果:
分类报告:
               precision    recall  f1-score   support


           0       0.72      0.73      0.73      4389
           1       0.73      0.72      0.72      4379


    accuracy                           0.73      8768
   macro avg       0.73      0.73      0.73      8768
weighted avg       0.73      0.73      0.73      8768


验证集：loss 0.566062, acc 0.726049, f1 0.726041

家里没有gpu就没往下训练了,你可以试一下  不过印象中模型最后会过拟合 所以有些参数需要调整下




------------------ 原始邮件 ------------------
发件人: "james"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 晚上9:02
收件人: "pengming617/text_matching"<text_matching@noreply.github.com>;
抄送: "彭明"<549639484@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [pengming617/text_matching] 验证集精度一直在0.5几附近徘徊 (#1)



好的，谢谢您！期待您的结果。
 不过论文中该模型的效果可以达到0.88，而且据说很多公司都在用esim这个模型，效果还不错。

**Comment by bzqweiyi** [comment]
好的，谢谢博主！
明天我在GPU上再调试下，看模型效果是否会有所提升。

**Comment by ljh9999** [comment]
作者您好，很感激您分享的代码，想请教您在infer.py的运行前，是如何调节输出结果中，判定为0/1的阈值的呢？输出结果当中的后一个array([[0.768, 0.231]])，有什么别的含义吗？
