### ISSUE TITLE
跑出来精度不高

### ISSUE THREAD

**Issue by will-wiki** [pengming617/text_matching#13]
您好，想问下为什么我ESIM模型跑出来精度一直不高在0.5-0.6上下，看了评论说l2改成0能提高但是我发现改了后甚至没有变化了

**Comment by pengming617** [comment]
有些参数可能需要修改下  建议重新拉一份代码  然后按这个参数试一试
self.l2_lambda = 0.0 
self.learning_rate = 0.001
self.dropout_keep_prob = 0.7
