### ISSUE TITLE
请问这个数据集发布是否经过官方同意的？如果没有的话，建议删除

### ISSUE THREAD

**Issue by twomeng** [pengming617/text_matching#17]

**Comment by pengming617** [comment]
这个都是开源的吧

**Comment by twomeng** [comment]
你可以去查数据集论文要求通过作者数据集申请信息才能获得，未经允许不得随意传播数据集。我是与数据集发布者沟通过的，请尽快删除。------------------ 原始邮件 ------------------
发件人: "pengming617"<notifications@github.com>
发送时间: 2019年12月19日(星期四) 中午11:40
收件人: "pengming617/text_matching"<text_matching@noreply.github.com>;
抄送: "twomeng"<937555373@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pengming617/text_matching] 请问这个数据集发布是否经过官方同意的？如果没有的话，建议删除 (#17)



这个都是开源的吧
 
&mdash;

**Comment by pengming617** [comment]
那我一会删除呗&nbsp; 网上太多咯




---原始邮件---
发件人: "twomeng"<notifications@github.com&gt;
发送时间: 2019年12月19日(周四) 中午1:10
收件人: "pengming617/text_matching"<text_matching@noreply.github.com&gt;;
抄送: "pengming617"<549639484@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [pengming617/text_matching] 请问这个数据集发布是否经过官方同意的？如果没有的话，建议删除 (#17)


你可以去查数据集论文要求通过作者数据集申请信息才能获得，未经允许不得随意传播数据集。我是与数据集发布者沟通过的，请尽快删除。------------------ 原始邮件 ------------------ 
 发件人: "pengming617"<notifications@github.com&gt; 
 发送时间: 2019年12月19日(星期四) 中午11:40 
 收件人: "pengming617/text_matching"<text_matching@noreply.github.com&gt;; 
 抄送: "twomeng"<937555373@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 
 主题: Re: [pengming617/text_matching] 请问这个数据集发布是否经过官方同意的？如果没有的话，建议删除 (#17) 
 
 
 
 这个都是开源的吧 
   
 &amp;mdash;
