### ISSUE TITLE
作者您好，很感激您分享的代码，想请教您在infer.py的运行前，是如何调节输出结果中，判定为0/1的阈值的呢？输出结果当中的后一个array([[0.768, 0.231]])，有什么别的含义吗？

### ISSUE THREAD

**Issue by ljh9999** [pengming617/text_matching#19]
作者您好，很感激您分享的代码，想请教您在infer.py的运行前，是如何调节输出结果中，判定为0/1的阈值的呢？输出结果当中的后一个array([[0.768, 0.231]])，有什么别的含义吗？

_Originally posted by @ljh9999 in https://github.com/pengming617/text_matching/issues/1#issuecomment-612616771_

**Comment by pengming617** [comment]
这是输入0/1这两个类的分数，哪个大就属于哪个类的

**Comment by ljh9999** [comment]
嗯，谢谢您的回复，我想请问这个的阈值在代码中是如何划分的呢
