### ISSUE TITLE
请问是不是漏掉DSSM的模型

### ISSUE THREAD

**Issue by sneffort** [pengming617/text_matching#3]
请问是不是漏掉DSSM的模型，谢谢

**Comment by yinhao2016** [comment]
你好，我貌似也发现DSSM模型的train.py不对，其实是PAIR-CNN的训练代码，作者可以更新下代码吗

**Comment by pengming617** [comment]
刚刚发现确实写错了，稍后会更更新下，谢谢指出问题！
