### ISSUE TITLE
DSSM模型里面给的train.py不对呀，作者可以更新下吗

### ISSUE THREAD

**Issue by yinhao2016** [pengming617/text_matching#4]
dssm下的train.py貌似是pair-cnn的train.py

**Comment by buptygz** [comment]
same problem

**Comment by buptygz** [comment]
> dssm下的train.py貌似是pair-cnn的train.py
你解决了吗？train.py不对的问题？

**Comment by pengming617** [comment]
刚刚看了下这个确实写错了，稍后会将其更新，谢谢指出问题
