### ISSUE TITLE
数据 预处理时候label取法

### ISSUE THREAD

**Issue by liumilan** [pengming617/text_matching#5]
hi,
  我看到数据预处理时候，取label时候，首先初始化成[0 0],如果这条数据label是1，那么就是[0 1]，如果这条数据label是0，那么就是[1 0]，这么做是有什么trick在里面吗？

**Comment by pengming617** [comment]
你好，我是这样理解的，这种one-hot的方法主要是在计算损失的时候用到的，分类的时候每个label对模型而言应该是一样的，假设一个样本的true label为3，预测为2和预测为1的时候这样在计算损失就不一样了。所以将他们转为one-hot的形式，是他们在计算损失的时候是一样的。
